### ISSUE TITLE
Scenario framework sometimes causes terminal to freeze

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#243]
#### Problem

Sometimes after interacting with Scenario objects, the terminal freezes and/or tries to print weird unprintable characters.

@BainanXia and I noticed this after the change to how we launch scenarios on the server (I think this is when it started happening, but I'm not 100% sure).

#### Theorizing

Maybe the `subprocess.Popen` call isn't compatible with the case where all serverside IO goes to `/dev/null`? Looking at the `subprocess` documentation, it seems like they recommend a call to `subprocess.run` unless more control is needed, and `Popen` is a lower-level object (maybe it doesn't always clean up after itself automatically?).

**Comment by merrielle** [comment]
Haven't seen in a long time
