### ISSUE TITLE
If a base profile is interrupted during download, it will be used to prepare an incomplete profile

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#246]
#### Problem

If a connection to the server is interrupted while a base profile is being downloaded (e.g. the VPN drops), an incomplete profile will be left in `~/ScenarioData`. This incomplete profile will then be used to prepare a profile for the server, which will cause the scenario run to fail when it reaches the missing data.

This edge case was created in https://github.com/Breakthrough-Energy/PowerSimData/pull/217, since the base profile download and the profile scaling/uploading are not all contained in the same `prepare_scenario_input()` method call. If the download is interrupted, `prepare_scenario_input()` still works because there's no check that the file that's downloaded is complete, just that it's there.

#### Potential solutions

Check that the length of downloaded base profiles is 8784 before using them to prepare simulation inputs. If not, either raise an Exception, prompt the user whether they want to re-downloaded, or do it automatically.

**Comment by danielolsen** [comment]
We managed to run into this problem again this week. I don't know the exact series of events that led to the partial file remaining after the interrupted download, but it is apparently still possible.

**Comment by jon-hagg** [comment]
Not sure how it was handled before, but since we currently download directly to the file (code [here](https://github.com/Breakthrough-Energy/PowerSimData/blob/develop/powersimdata/data_access/profile_helper.py#L28)), this is expected. We could download to a temp file instead, so it is all or nothing.
