### ISSUE TITLE
Modify TAMU network cost curves so that larger generators are cheaper than smaller ones

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#280]
### Problem

Eastern coal: ![image.png](https://images.zenhubusercontent.com/5db9cf1dced9000001183fb3/d0a4ea99-870f-4b70-8809-79a67b228a99)

Eastern gas: ![image.png](https://images.zenhubusercontent.com/5db9cf1dced9000001183fb3/0042ed80-a673-4ca8-bf81-6114eb347a69)

Figures come from @BainanXia's spot check script, run on scenario 462. See cell [45] in `USA Basecase 2016 spot check.ipynb` or `USA Basecase 2016 spot check.html` in `Explorations/BainanX/spot check script integration`.

Larger generators should be cheaper, not more expensive. Western & Texas aren't _as_ bad (the correlation isn't strongly in the wrong direction) but still don't show the efficiencies we would expect for larger generators.

### Goals

- Make larger generators cheaper than smaller generators
- Maintain similar average LMPs (by interconnection) as in our previous 2016 USA base case
- Maintain similar levels of congestion as in our previous 2016 USA base case

**Comment by merrielle** [comment]
partially resolved, not going to do further work
