### ISSUE TITLE
Specify grid model in building phase of a scenario

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#351]
Allow the user to select the grid model when building a scenario.

**Comment by danielolsen** [comment]
One thing that we discussed in today's meeting was the need to make sure that users of old versions of the software do not accidentally introduce bad data into the ScenarioList, or even worse overwrite pre-existing good data. One idea discussed:
- Moving the location of the ScenarioList to a new path, e.g. `/mnt/bes/pcm/ScenarioList.csv` -> `/mnt/bes/pcm/v0.4/ScenarioList.csv` or `/mnt/bes/pcm/ScenarioList_v0.4.csv`. Then users of the old code can't accidentally mangle the new version of the table.
