### ISSUE TITLE
Handle USA profiles

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#415]
Download profiles from blob storage

**Comment by jon-hagg** [comment]
Profiles are located in the `profiles` container in our bescienceswebsite [storage account](https://portal.azure.com/#@gatesventures.com/resource/subscriptions/237d7726-5ddd-4568-936a-02c3236a712f/resourceGroups/CENACS/providers/Microsoft.Storage/storageAccounts/bescienceswebsite/overview).

For example, the demand profile is located [here](https://bescienceswebsite.blob.core.windows.net/profiles/usa_tamu/demand_vJan2021.csv). I'll probably add a metadata file listing the versions to enable the same functionality in the code without depending on the official azure sdk (don't need all the features, we can just use `requests.get`).
