### ISSUE TITLE
param str/list interconnect: interconnect name(s).

### ISSUE THREAD

**Issue by LFPower** [Breakthrough-Energy/PowerSimData#436]
https://github.com/Breakthrough-Energy/PowerSimData/blob/934c62a20691a4d75932471759fc974ed5937b9b/powersimdata/input/grid.py#L15

It would be good to list the interconnect names in the comments, otherwise it takes time to figure out the correct interconnect names.

The following is what I found in the script /networt/usa_tamu/model.py

possible = ["Eastern", "Texas", "Western", "USA"]

**Comment by rouille** [comment]
Note that this list is not definitive.. If one day we have a model of the European grid, `possible` will then be extended.
