### ISSUE TITLE
Improve flexibility of congested branch upgrade algorithm

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#439]
### Background

Currently, in `powersimdata.design.transmission.upgrade.scale_congested_mesh_branches`, we estimate the benefit of upgrading a branch based on its `(shadow prices in 95th percentile of hours for a reference scenario)`, divided by the 'cost' of `{1, MW capacity in base grid, or MW-miles in base grid}` for the `"branches"`, `"MW"`, and `"MWmiles"` methods, respectively (controlled by the `method` parameter.

The 95th percentile is user-override-able, but the user cannot choose other ways of estimating the benefit part of the equation.

When this algorithm was originally developed, MW-miles was the best proxy for cost that we had, but not we have per-branch cost estimation methods in the investment cost module.

### Improved options
- [ ] Allow the user to choose between a percentile-base method or a mean-based method for estimating benefit (or other additional method)
- [x] Allow the user to choose cost estimation based on the investment cost analysis module. This will be slower, but more accurate, since the per-MW-mile cost of higher-voltage lines should be better than lower-voltage ones, and certain locations have higher cost multipliers than others. (Done via https://github.com/Breakthrough-Energy/PowerSimData/pull/452)
- [ ] Allow the algorithm to suggest the addition of new higher-voltage parallel lines between substations. This is definitely a stretch goal, but e.g. if we have a heavily congested 69 kV line between two substations that have 138 kV buses, we could add a new 138 kV branch, rather than just assuming that congestion will always be solved by adding parallel branches of the same voltage (effectively what we're doing now by linearly scaling rating and impedance).

**Comment by danielolsen** [comment]
I've gotten started on the cost angle, it's a bit tricky because while we can get individual branch upgrade costs, the indices don't line up with the original branch IDs because of the pandas `merge`s within the AC cost calculation. Finding this problem was annoying but the fix shouldn't be too bad, I should have a PR up sometime this week.

**Comment by BainanXia** [comment]
> I've gotten started on the cost angle, it's a bit tricky because while we can get individual branch upgrade costs, the indices don't line up with the original branch IDs because of the pandas `merge`s within the AC cost calculation. Finding this problem was annoying but the fix shouldn't be too bad, I should have a PR up sometime this week.

I don't quite understand but hopefully will get more info in the up coming PR🙏

**Comment by danielolsen** [comment]
Here's a code snippet to demonstrate. Scenario 3203 is a Western scenario, with 466 upgraded transmission lines, but when we call `calculate_ac_inv_costs` with `sum_results=False`, we get back a dataframe where the index is `0..465`. To properly divide our branch congestion metric by our estimated upgrade costs, we want the costs dataframe to line up with the congestion dataframe (which still has the proper indices). The indices get lost when we do `pandas.DataFrame.merge`.
```python
>>> from powersimdata.scenario.scenario import Scenario
>>> from powersimdata.design.investment.investment_costs import calculate_ac_inv_costs
>>> scenario = Scenario(3203)
Transferring ScenarioList.csv from server
100%|#######################################| 643k/643k [00:00<00:00, 4.90Mb/s]
Transferring ExecuteList.csv from server
100%|######################################| 48.2k/48.2k [00:00<00:00, 699kb/s]
SCENARIO: Terrapower | Western_90pctclean_30pctnuclear_0pctflex_OB1_Mesh50x14t40

--> State
analyze
--> Loading grid
Transferring ScenarioList.csv from server
100%|#######################################| 643k/643k [00:00<00:00, 6.41Mb/s]
Loading bus
Loading plant
Loading heat_rate_curve
Loading gencost_before
Loading gencost_after
Loading branch
Loading dcline
Loading sub
Loading bus2sub
--> Loading ct
>>> ac_costs = calculate_ac_inv_costs(scenario, sum_results=False)
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading sub.csv
Reading bus2sub.csv
Reading zone.csv
>>> ac_costs["line_cost"]
     from_bus_id  to_bus_id         r  ...   lengthMi          MWmi          Cost
0        2010118    2010186  0.003228  ...   3.966407   1057.444153  4.680032e+06
1        2010585    2010606  0.005501  ...  19.116503   3216.542810  1.423576e+07
2        2010600    2010606  0.005831  ...   6.779398   1310.525496  5.800118e+06
3        2010618    2010876  0.046418  ...  43.236124   9233.506605  4.086561e+07
4        2010618    2010968  0.009910  ...  54.634905  11388.099526  5.040140e+07
..           ...        ...       ...  ...        ...           ...           ...
461      2077139    2077148  0.005261  ...   9.988321   2249.569591  9.956135e+06
462      2077152    2077148  0.008695  ...  20.615643   4535.647571  2.007385e+07
463      2077147    2077140  0.008870  ...  10.230922   1974.874790  8.740392e+06
464      2077281    2077203  0.004805  ...   3.791034    612.858483  2.712386e+06
465      2080016    2080024  0.000699  ...   0.215456     30.194038  1.336326e+05

[466 rows x 44 columns]
>>> branch = scenario.state.get_grid().branch
>>> branch.index
Int64Index([ 88209,  88210,  88211,  88212,  88213,  88214,  88215,  88216,
             88217,  88218,
            ...
            104182, 104183, 104184, 104185, 104186, 104187, 104188, 104189,
            104190, 104191],
           dtype='int64', name='branch_id', length=12730)
>>>
```

**Comment by BainanXia** [comment]
> Here's a code snippet to demonstrate. Scenario 3203 is a Western scenario, with 466 upgraded transmission lines, but when we call `calculate_ac_inv_costs` with `sum_results=False`, we get back a dataframe where the index is `0..465`. To properly divide our branch congestion metric by our estimated upgrade costs, we want the costs dataframe to line up with the congestion dataframe (which still has the proper indices). The indices get lost when we do `pandas.DataFrame.merge`.
> 
> ```python
> >>> from powersimdata.scenario.scenario import Scenario
> >>> from powersimdata.design.investment.investment_costs import calculate_ac_inv_costs
> >>> scenario = Scenario(3203)
> Transferring ScenarioList.csv from server
> 100%|#######################################| 643k/643k [00:00<00:00, 4.90Mb/s]
> Transferring ExecuteList.csv from server
> 100%|######################################| 48.2k/48.2k [00:00<00:00, 699kb/s]
> SCENARIO: Terrapower | Western_90pctclean_30pctnuclear_0pctflex_OB1_Mesh50x14t40
> 
> --> State
> analyze
> --> Loading grid
> Transferring ScenarioList.csv from server
> 100%|#######################################| 643k/643k [00:00<00:00, 6.41Mb/s]
> Loading bus
> Loading plant
> Loading heat_rate_curve
> Loading gencost_before
> Loading gencost_after
> Loading branch
> Loading dcline
> Loading sub
> Loading bus2sub
> --> Loading ct
> >>> ac_costs = calculate_ac_inv_costs(scenario, sum_results=False)
> Reading bus.csv
> Reading plant.csv
> Reading gencost.csv
> Reading branch.csv
> Reading dcline.csv
> Reading sub.csv
> Reading bus2sub.csv
> Reading zone.csv
> >>> ac_costs["line_cost"]
>      from_bus_id  to_bus_id         r  ...   lengthMi          MWmi          Cost
> 0        2010118    2010186  0.003228  ...   3.966407   1057.444153  4.680032e+06
> 1        2010585    2010606  0.005501  ...  19.116503   3216.542810  1.423576e+07
> 2        2010600    2010606  0.005831  ...   6.779398   1310.525496  5.800118e+06
> 3        2010618    2010876  0.046418  ...  43.236124   9233.506605  4.086561e+07
> 4        2010618    2010968  0.009910  ...  54.634905  11388.099526  5.040140e+07
> ..           ...        ...       ...  ...        ...           ...           ...
> 461      2077139    2077148  0.005261  ...   9.988321   2249.569591  9.956135e+06
> 462      2077152    2077148  0.008695  ...  20.615643   4535.647571  2.007385e+07
> 463      2077147    2077140  0.008870  ...  10.230922   1974.874790  8.740392e+06
> 464      2077281    2077203  0.004805  ...   3.791034    612.858483  2.712386e+06
> 465      2080016    2080024  0.000699  ...   0.215456     30.194038  1.336326e+05
> 
> [466 rows x 44 columns]
> >>> branch = scenario.state.get_grid().branch
> >>> branch.index
> Int64Index([ 88209,  88210,  88211,  88212,  88213,  88214,  88215,  88216,
>              88217,  88218,
>             ...
>             104182, 104183, 104184, 104185, 104186, 104187, 104188, 104189,
>             104190, 104191],
>            dtype='int64', name='branch_id', length=12730)
> >>>
> ```

Make sense. Thanks for the detailed demonstration. A quick fix could be `reset_index` before and `set_index` after `merge` to fix it.

**Comment by danielolsen** [comment]
@BainanXia exactly. Here's the one-liner function that seems to do the trick:
```python
def merge_keep_index(df1, df2, **kwargs):
        return df1.reset_index().merge(df2, **kwargs).set_index(df1.index.names)
```
so instead of `df1.merge(df2, **kwargs)`, we do `merge_keep_index(df1, df2, **kwargs)` and that fixes this problem. There's another bug somewhere that still leads to a couple of individual `NaN` values in the cost calculation somehow.

I mostly just wanted to post an update so that no one else would start working on this in the meantime and waste time tracking down this bug.
