### ISSUE TITLE
Allow calculate_mw_miles to be used for Scenario in Create state

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#457]
Currently, this fails with the following traceback:
```python
c:\python38\lib\site-packages\powersimdata\design\transmission\mwmiles.py in calculate_mw_miles(scenario, exclude_branches)
     15     """
     16 
---> 17     original_grid = Grid(scenario.info["interconnect"].split("_"))
     18     ct = scenario.state.get_ct()
     19     upgrades = _calculate_mw_miles(original_grid, ct, exclude_branches)

c:\python38\lib\site-packages\powersimdata\scenario\scenario.py in __getattr__(self, name)
     56             return getattr(self.state, name)
     57         elif hasattr(self.state, "__getattr__"):
---> 58             return self.state.__getattr__(name)
     59         else:
     60             raise AttributeError(

c:\python38\lib\site-packages\powersimdata\scenario\create.py in __getattr__(self, name)
     67             raise AttributeError(f"Call set_grid first to access {name} attribute")
     68         else:
---> 69             raise AttributeError(f"Create object has no attribute {name}")
     70 
     71     def __setattr__(self, name, value):

AttributeError: Create object has no attribute info
```

It is using our fancy new state attribute passthrough, but the failure really originates because we don't have an `info` attribute for the Scenario object. We can use a workaround via the `_calculate_mw_miles` function which takes a Grid object, instead of a Scenario, but it would be nice if we could avoid the use of this private function, which mostly exists for testability purposes (since instantiating a base Grid for a MockScenario is tricky).

**Comment by rouille** [comment]
We use `_scenario_info` in in the `Create`, `Execute` and `Analyze` classes. Could we use `info` instead to be consistent with the `Scenario` class?

**Comment by rouille** [comment]
@ahurli, @jon-hagg, do you see any issue that could arise from this renaming?

**Comment by danielolsen** [comment]
For a Scenario in Analyze state, `scenario.info` and `scenario.state._scenario_info` point to the same object; i.e. `scenario.info is reference_scenario.state._scenario_info` evaluates to `True`. Can we add something to the Scenario in Create state to achieve the same thing? Then we could successfully access `scenario.info` without inadvertently breaking anything that expects to be able to access `State._scenario_info`.

**Comment by rouille** [comment]
> For a Scenario in Analyze state, `scenario.info` and `scenario.state._scenario_info` point to the same object; i.e. `scenario.info is reference_scenario.state._scenario_info` evaluates to `True`. Can we add something to the Scenario in Create state to achieve the same thing? Then we could successfully access `scenario.info` without inadvertently breaking anything that expects to be able to access `State._scenario_info`.

I guess we could do:
```
self._scenario_info = scenario.info
```
in the constructor of the `Create` class and do:
```
if not descriptor:
    self.info = OrderedDict(
            [
                ("plan", ""),
                ("name", ""),
                ("state", "create"),
                ("grid_model", ""),
                ("interconnect", ""),
                ("base_demand", ""),
                ("base_hydro", ""),
                ("base_solar", ""),
                ("base_wind", ""),
                ("change_table", ""),
                ("start_date", ""),
                ("end_date", ""),
                ("interval", ""),
                ("engine", ""),
            ]
        )
    self.state = Create(self)
else:
    ...
```
in the `Scenario` class

**Comment by rouille** [comment]
@danielolsen, can you try th 

> > For a Scenario in Analyze state, `scenario.info` and `scenario.state._scenario_info` point to the same object; i.e. `scenario.info is reference_scenario.state._scenario_info` evaluates to `True`. Can we add something to the Scenario in Create state to achieve the same thing? Then we could successfully access `scenario.info` without inadvertently breaking anything that expects to be able to access `State._scenario_info`.
> 
> I guess we could do:
> 
> ```
> self._scenario_info = scenario.info
> ```
> 
> in the constructor of the `Create` class and do:
> 
> ```
> if not descriptor:
>     self.info = OrderedDict(
>             [
>                 ("plan", ""),
>                 ("name", ""),
>                 ("state", "create"),
>                 ("grid_model", ""),
>                 ("interconnect", ""),
>                 ("base_demand", ""),
>                 ("base_hydro", ""),
>                 ("base_solar", ""),
>                 ("base_wind", ""),
>                 ("change_table", ""),
>                 ("start_date", ""),
>                 ("end_date", ""),
>                 ("interval", ""),
>                 ("engine", ""),
>             ]
>         )
>     self.state = Create(self)
> else:
>     ...
> ```
> 
> in the `Scenario` class

Can you implement this and see if `calculate_mw_miles` still raises an error?

**Comment by danielolsen** [comment]
I can confirm this works. Tested using the newly-pushed `daniel/add_info_to_create` branch.
