### ISSUE TITLE
Add function to create profiles without uploading to the server

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#482]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish there was a way to write the profiles for a scenario to CSVs without the requirement to interact with the server. This would be useful for troubleshooting, as well as for passing profiles as inputs to other workflows (e.g. as inputs to capacity expansion). This would be the profile analog to what we did for being able to export a Grid to a case.mat file without touching the server (see #406).

### Describe your proposed implementation

There should be a function with a name like 'export_profiles' which would take a grid, profile versions (probably as a dict, with keys overlapping with the `scenario_info` so that the profile export could use this same dict or just the required keys), and a change table, and write each of the profiles to a CSV in a given folder, using the same TransformProfile-based workflow internally but without any file moves/uploads. The current `prepare_profile` function could be refactored to use this function, and then also perform the required moves/uploads.

**Comment by rouille** [comment]
Should I take care of it? It seems this will needed once github/Breakthrough-Energy/SwitchWrapper#56 is merged

**Comment by danielolsen** [comment]
> Should I take care of it? It seems this will needed once github/[Breakthrough-Energy/SwitchWrapper#56](https://github.com/Breakthrough-Energy/SwitchWrapper/pull/56) is merged

You are probably the most knowledgeable about the chain through `Execute -> TransformProfile -> InputData -> etc.`
