### ISSUE TITLE
Ingest profiles for potential electrification, and incorporate them into Scenario preparation

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#574]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish that the software, during preparation of a Scenario, would:
- ingest not only profiles of current demand, but also one or more profiles which represent potential electrification futures (e.g. building electrification, transportation electrification),
- allow the user to specify how much of this potential electrification is expected,
- and would include this addition demand during Scenario preparation, so that it is included in the simulation.

Note: for the purposes of this issue, I would consider this demand to be inflexible, so this functionality is distinct from that of #511.

### Describe your proposed implementation

- One or more additional demand CSVs would live in the blob storage, and be cached locally.
- The `ChangeTable` class would get new methods which allow the use to specify how much electrification is expected for each additional demand CSV, on either a grid-wide basis or by zone.
- The `Execute.prepare_simulation_input` method would either combine all demand into a single `demand.csv` file for ingestion by the simulation engine, or if the simulation engine can take multiple demand profiles and ingest them, then they could be created & uploaded separately.

To get a little more detailed on how we plan to ingest CSVs:
- Every profile as ingested by PowerSimData has an identical shape: indices are hourly timestamps, columns are zone IDs, values are megawatts. We may expand this later to be able to have unique per-bus profiles, but for now we stay in zones.
- For the electrification profiles, they represent the electrical demand that would be seen by the grid if 100% of the existing fossil-fuel consumption that serves that underlying need (e.g. the need to heat buildings, the need for transportation) were being satisfied with electric equivalents.
- ~Within each 'class' of electrification (e.g. Buildings, Transportation, etc.) we have multiple different types of technologies (e.g. Buildings has different technologies of heat pumps, Transportation has different technologies of electric vehicles).~
- **EDIT**: Within each 'class' of electrification (e.g. Buildings, Transportation, etc.), we have multiple different 'end uses' (e.g. commercial heating vs. residential hot water, or light duty vehicles vs. light duty trucks). Within each end use, we have multiple different 'technologies' (e.g. different heat pump technologies, EV models with different ranges).
- The 'final' profile for a given zone (i.e. what's prepared and gets sent to the simulation engine) is the zone's 'base' demand (multiplied by a scaling factor which defaults to one) plus an 'aggregate' profile for each electrification 'class'. The aggregate profile is the sum of each technology's profile multiplied by that technology's scaling factor, and all scaling factors within a given 'class' should be non-negative and sum to no more than 1, since we can't replace the fossil fuel usage that supplies a given heating/transportation need by more than one simultaneous electrified technology. We could have a mix of electrification within a zone, e.g. 50% standard heat pumps and 30% advanced performance heat pumps, but not 50% + 60%.
- All scaling factors should be independently controllable for each zone.
- For each 'class' of electrification, for each technology choice, we may have multiple different versions of the profile, of which the user can only select one. E.g. for transportation electrification, for cars with 100-miles range, we may have different profiles which assume different levels of transport need, e.g. a 'current level of public transportation' profile and an 'increased public transportation' profile; for buildings, we may have different profiles based on the degree of new construction. The creation of these different profiles is external to the Scenario framework: we just need to assume that we have at least one profile for each technology.

### Additional context
This is still early design stage, so any input is welcome.

**Comment by lanesmith** [comment]
While they may be more discrete (i.e., a limited set of electrification scenarios, technology advancements, and years) than you have in mind for this feature, this might be a good opportunity to consider the ability to specify the EFS demand profiles as well. In `PreREISE`, we have the ability to create demand profiles in the zonal shape recognized by the `usa_tamu` grid model. Despite some of their shortcomings (lack of geographical granularity, potential underestimations of winter demand peaks), the familiarity of the EFS demand data might be a useful option or benchmark for users.

This may be off topic for this particular issue, but one thing that I wonder about with the integration of any new demand (from the collaborators or the EFS demand profiles) is how weather years are managed. For instance, I believe the EFS demand profiles are based on 2013 data, which is different than the weather data that has been used for BE's other profiles. Do these tools have the means to support acquiring/building solar, wind, and hydro profiles for other weather years that align with the selected demand profile?

**Comment by BainanXia** [comment]
@lanesmith That's a good point. So far we've never considered supporting multiple weather years in profile selection when creating a scenario. In all previous runs, base profiles are scaled to ones of the target year according to capacity projections or growth assumptions.

**Comment by danielolsen** [comment]
For the current integrated profiles (demand, hydro, solar, wind), I think we have more flexibility to build profiles for several different recent weather years. I imagine we'll have them up on the blob storage for the user to choose soon.

Going back to 2013 data can be tough, since many of the data sources weren't recording/publishing back then, or the old data are archived and less available. Maybe if we want to be most accurate when looking at the EFS profiles, we would want to pick the closest available weather year.

There's probably no easy way to re-generate the EFS profiles for a different year, is there?

**Comment by BainanXia** [comment]
We will definitely want all profiles aligned with same weather year during scenario creation and should be able to provide alternatives if some profile for certain year is not provided by us, but the users could choose build it on the fly via our existing methods/assumptions (such as scale it based on the ones we have) or provide themselves.

**Comment by lanesmith** [comment]
> Going back to 2013 data can be tough, since many of the data sources weren't recording/publishing back then, or the old data are archived and less available. Maybe if we want to be most accurate when looking at the EFS profiles, we would want to pick the closest available weather year.

I'm not sure if this is out there, but I'd be curious to see if there are similarity scores for comparing weather years. If so, this would be particularly useful for situations like this where there is access to recent years, but less access to older years. While complete alignment would be preferred, at least having similar weather patterns might be a reasonable approximation.

> There's probably no easy way to re-generate the EFS profiles for a different year, is there?

Probably not an easy way. NREL offered a pretty decent description of their process and included most (if not all) of their data projections through 2050 that are used to populate EnergyPATHWAYS. Considering that the collaborators are developing their models, it might not be worth it to replicate that process.

**Comment by jon-hagg** [comment]
Just realized that after adding end uses to the schema, I'm not sure what the profiles would be. For example, would we have them in the form `[end use]_[technology]_[version].csv`? I didn't see an obvious way to aggregate if it was just the technology or just the end use (or if it even makes physical sense).

**Comment by danielolsen** [comment]
I think we want at least `[class]_[end use]_[technology]_[version].csv`, e.g. `buildings_reshotwater_advperfhp_2020.csv`. They're going to get quite long, especially if we want to have things like weather year 2020 + version generated in March 2022.

**Comment by rouille** [comment]
> I think we want at least `[class]_[end use]_[technology]_[version].csv`, e.g. `buildings_reshotwater_advperfhp_2020.csv`. They're going to get quite long, especially if we want to have things like weather year 2020 + version generated in March 2022.

The weather year won't be part of the timestamp (indices)?

**Comment by danielolsen** [comment]
Weather year should definitely be in there, since for the buildings folks one of their big value adds is that they have a bunch of different weather years. I guess `[version]` will be some combination of weather year and potentially when we generated the profile.
