### ISSUE TITLE
Refactor the Modelmmutables to better represent non-USA grid models

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PowerSimData#591]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
Currently, instantiating a `Grid` object requires a instantiation of a `ModelImmutables` object, which contains system-level constants. Information about generator types and default values for new storage is fine, but there's a lot of stuff in `ModelImmutables.zones`/`zones.py` that doesn't correspond primarily to zones (which matter to distribution of demand profiles to buses), but to higher-level areas like states or time zones, which don't necessarily apply to other regions. These sorts of information aren't important for the simulation, but are used for post-processing of results. The `area_to_loadzone` methods has some hard-coded references to states, and no references to other regions (e.g. countries, provinces).

### Describe your proposed implementation

At the very least, `area_to_loadzone` needs a refactor to handle things like provinces, countries, etc. At the same time, we may want to reorganize the structure so that there can be some sets of information that are defined at a higher-level than just a grid model, e.g. information that's defined for a given region, or for given fuels, etc., rather than manually duplicating it within the subfolders of `powersimdata.network`. #566 did things quick-and-dirty, but there's definitely a lot that can be improved about the process of adding new grid models, like having as much data as possible stored in CSVs rather than python modules.

**Comment by merrielle** [comment]
Ben has finished this
