### ISSUE TITLE
Simulation fails when using Native setup

### ISSUE THREAD

**Issue by lanesmith** [Breakthrough-Energy/PowerSimData#598]
- [x] I have checked that this issue has not already been reported.

### Bug summary
When trying to run simulations using the [Native setup](https://breakthrough-energy.github.io/docs/user/installation_guide.html#natively), the process fails when trying to run the scenario in `REISE.jl` (after the scenario has been created). The most surprising part is that a simulation can be set up using `PowerSimData` and then successfully run in the standalone version of `REISE.jl`.

### Code for reproduction
This occurs sometime after using the `launch_simulation` functionality of a scenario in the execute state. It does not fail immediately or throw an error. The only way you know it failed is through the `print_scenario_status` and `check_progress` functions. The scenario that was created for this example closely matches the one listed in the [documentation](https://breakthrough-energy.github.io/docs/powersimdata/index.html#creating-a-scenario), with the exception that a change table was not created.

### Actual outcome
The following output is obtained by using the `check_progress` functionality on the scenario:
```shell
{1: {'scenario_id': '1',
  'output': ['Validation complete!',
   'Launching scenario with parameters:',
   "{'num_segments': 1, 'interval': 24, 'n_interval': 3, 'start_index': 1, 'input_dir': 'C:\\\\Users\\\\LaneSmith\\\\ScenarioData\\\\tmp\\\\scenario_1', 'execute_dir': 'C:\\\\Users\\\\LaneSmith\\\\ScenarioData\\\\tmp\\\\scenario_1\\\\output', 'threads': None, 'julia_env': None, 'solver_kwargs': None}",
   "Exception 'LoadError' occurred while calling julia code:",
   'const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))'],
  'errors': [],
  'status': None}}
```
The simulation starts fine, as can be seen by the fact that validation is completed and the settings are printed (both of which occur in `REISE.jl/pyreisejl/utility/launchers.py`), indicating that there isn't a problem with finding the `REISE.jl` directory (specified as `ENGINE_DIR` in the `config.ini` file).

### Expected outcome
The expected outcome is for the simulation to be executed successfully. As mentioned in the initial summary, that is the outcome that is observed when running the standalone version of `REISE.jl`, indicating that the bulk of the functionality is sound (at least most of it anyway, the standalone version does not need to run `REISE.jl/pyreisejl/utility/app.py`) and the scenario files are not formatted incorrectly. It appears that the simulation is failing when entering the `init_julia` function in `REISE.jl/pyreisejl/utility/launchers.py`. 

### Environment
Please specify your platform and versions of the relevant libraries you are using:
* Operating system: Windows 10
* Python version: Python 3.8.3
* Jupyter version: Julia 1.5.4

I'm using the current develop branches of both `PowerSimData` and `REISE.jl`.

### Additional context
As I mentioned above, one of the main differences between running a simulation through the `PowerSimData`-`REISE.jl` interface and the standalone version of `REISE.jl` is that the `PowerSimData`-`REISE.jl` interface uses `REISE.jl/pyreisejl/utility/app.py`. Within `app.py`, there appears to be a copy of the system environment that is created (via the `run_script` function). Perhaps the copied system environment doesn't actually have the Julia-related dependencies installed? If that is the case, then having the ability to specify the Julia environment probably doesn't do much good (which I've worked on extending from only being in `REISE.jl` to being specifiable in `PowerSimData`) unless we also set up the functionality to install the dependencies in the copied system environment. Is there a way for the Native setup to work without creating the copied system environment?

**Comment by lanesmith** [comment]
@jon-hagg and I were able to find a solution to this problem. It appears that `REISE.jl` needs to be activated and instantiated (see [option 3 in our `REISE.jl` documentation](https://github.com/Breakthrough-Energy/REISE.jl#julia-package-installation) and the related discussion in the [Julia documentation](https://pkgdocs.julialang.org/v1/environments/#Using-someone-else's-project)), as opposed to just `dev`-ed, which is how I initially had it set up and how it originally worked with my standalone version of `REISE.jl`. I'm still not fully sure why the `dev`-ing process works with the standalone version of `REISE.jl`, but not when trying to use `REISE.jl` through `PowerSimData`.

While there might need to be some more research into the merits of `add`-ing vs. `dev`-ing vs. activating and instantiating `REISE.jl`, we will probably need to update the documentation for the [Native setup](https://breakthrough-energy.github.io/docs/user/installation_guide.html#natively) and potentially the [`REISE.jl` documentation](https://github.com/Breakthrough-Energy/REISE.jl#julia-package-installation).

**Comment by rouille** [comment]
> @jon-hagg and I were able to find a solution to this problem. It appears that `REISE.jl` needs to be activated and instantiated (see [option 3 in our `REISE.jl` documentation](https://github.com/Breakthrough-Energy/REISE.jl#julia-package-installation) and the related discussion in the [Julia documentation](https://pkgdocs.julialang.org/v1/environments/#Using-someone-else's-project)), as opposed to just `dev`-ed, which is how I initially had it set up and how it originally worked with my standalone version of `REISE.jl`. I'm still not fully sure why the `dev`-ing process works with the standalone version of `REISE.jl`, but not when trying to use `REISE.jl` through `PowerSimData`.
> 
> While there might need to be some more research into the merits of `add`-ing vs. `dev`-ing vs. activating and instantiating `REISE.jl`, we will probably need to update the documentation for the [Native setup](https://breakthrough-energy.github.io/docs/user/installation_guide.html#natively) and potentially the [`REISE.jl` documentation](https://github.com/Breakthrough-Energy/REISE.jl#julia-package-installation).

I am working on the documentation. Should we simply drop the `add`ing and `dev`ing of REISE.jl in the installation notes? What do you think @danielolsen and @BainanXia?

**Comment by rouille** [comment]
> 

Sounds good

**Comment by jon-hagg** [comment]
My understanding of our debugging session was that we would need to `activate`, then `instantiate`, then `add GLPK` (or preferred solver). The `add` will update the project and manifest toml files, so might also be worth adding common solvers to those to save a step. Also we learned that `st` or `status` is basically a bunch of pointers to packages defined by `Manifest.toml`, so undoing the changes made by adding a solver is immediately reflected in the julia environment. I'm not really sure how `dev` works, maybe it still does. Also, I think the [JULIA_PROJECT](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_PROJECT) environment variable passed by powersimdata is what tells julia to use the `REISE` environment instead of the default (just wanted to confirm this since we were unclear on that before).

**Comment by lanesmith** [comment]
> My understanding of our debugging session was that we would need to `activate`, then `instantiate`, then `add GLPK` (or preferred solver). The `add` will update the project and manifest toml files, so might also be worth adding common solvers to those to save a step. 

I went back and retested with `Gurobi` not being included in the `REISE` environment and it still worked in both the Native setup and the standalone version of `REISE.jl`. I think this still works because when packages are imported for the different launchers (as seen in `pyreisejl/utility/launchers.py`), each solver is specified independently of the `REISE` module. Perhaps the `REISE not found` error was being thrown because `REISE`, as a module, needs to be activated and instantiated whereas the solver packages only need to be added (i.e., present in the list of base Julia packages but not necessarily in the environment)?

@danielolsen, I'm curious about your comment on the commercial solvers being a pain to always install. Wouldn't the package (e.g., the `Gurobi` package) only need to be installed when you first activate and instantiate `REISE`? Even on future instantiations, the commercial solver package would probably only need to be reinstalled if its version changed. Do all of the packages in the environment get compiled when you use a particular environment or only when specified (i.e., through `import` or `using`)?

**Comment by danielolsen** [comment]
> Wouldn't the package (e.g., the Gurobi package) only need to be installed when you first activate and instantiate REISE?

My thinking is: we do this every time we test the package. It would be nice to avoid unnecessarily downloading something that won't be used, and can't be used without a license key.

**Comment by lanesmith** [comment]
Thanks for clarifying, I hadn't thought about testing.

**Comment by lanesmith** [comment]
This issue was closed by [REISE.jl PR #174](https://github.com/Breakthrough-Energy/REISE.jl/pull/174).
