### ISSUE TITLE
Question - Is there any plan to making the underlying data more accessible for geospatial scientists?

### ISSUE THREAD

**Issue by zacharyDez** [Breakthrough-Energy/PowerSimData#654]
I just found your project, and what astonished to see some of the dashboard results. Incredible to have a map of our grid with such details!

However, it took me quite some time to dive into the underlying datasets in the initial CSVs. As a result, understanding the many to many relationships between the entities is not intuitive. 

I wondered if there were any plans to make the underlying data more accessible for geospatial scientists who want to run spatial or network analysis with standard tools from other ecosystems. 

I will design a data pipeline that loads the CSVs to PostGIS and performs basic transformations. If there is some way that I can give back to the project, I would gladly do so.

**Comment by yixingxu** [comment]
Hi Zachary,

Thanks for your interest in using our data and we highly appreciate it if you are also interested in contributing to the project!

Extracting GIS information from CSVs to any other format should be easy. We have geographic coordinates for every substation in the base grid, which can be found in sub.csv. Note that multiple buses can share the same coordinate if they locate in the same substation. Designing a data pipeline to streamline such process is a great idea which could be helpful for future interdisciplinary work. Unfortunately, our team is tied up with other priorities for the time being and it would be great if you can further specify your request via our [feature request template](https://github.com/Breakthrough-Energy/.github/blob/main/.github/ISSUE_TEMPLATE/feature_request.md). 

We do have some interesting open issues. If you would like to contribute to open issues, we suggest to start with [contribution guideline](https://breakthrough-energy.github.io/docs/dev/contribution_guide.html#) and bring up any questions along the process in our [slack community](https://join.slack.com/t/besciencescommunity/shared_invite/zt-or95p3pi-kO1pj1b6O64THiHU9bgzkA).

Just in case you might be interested, we are working on a new version of the grid model using [Homeland Infrastructure Foundation-Level Data](https://hifld-geoplatform.opendata.arcgis.com/datasets/electric-power-transmission-lines/explore?location=33.766174%2C-111.104115%2C3.39) (HIFLD). We will use the same data format as the current grid model and will update corresponding entries accordingly.

I know it is a lot of information and you may have questions. You are welcome to join our [slack community](https://join.slack.com/t/besciencescommunity/shared_invite/zt-or95p3pi-kO1pj1b6O64THiHU9bgzkA) to discuss in details!

**Comment by BainanXia** [comment]
Closing this issue since further discussions will be handled elsewhere. Thanks @zacharyDez
