### ISSUE TITLE
Battery cycling

### ISSUE THREAD

**Issue by Mingze-Li128** [Breakthrough-Energy/PowerSimData#684]
# :beetle:

- [ ] I have checked that this issue has not already been reported.

### Bug summary
We add 4 batteries in the Texas grid. However, the battery solution looks weird, and we didn’t see the battery is doing any cycling.

We enforced the terminal SOC to be fixed at 50% of maximum SOC and expected the battery to reach to terminal SOC regardless of the economically consideration. However, we were also not seeing the desired terminal SOC.

### Code for reproduction
```
scenario.change_table.add_storage_capacity(
    [
        {"bus_id": 3002011, "capacity": 750, "duration": 1, "terminal_max": 0.9, "terminal_min": 0.1, "OutEff": 1, "InEff": 1, "energy_value": 5},
        {"bus_id": 3003048, "capacity": 750, "duration": 1, "terminal_max": 0.9, "terminal_min": 0.1, "OutEff": 1, "InEff": 1, "energy_value": 5},
        {"bus_id": 3005055, "capacity": 750, "duration": 1, "terminal_max": 0.9, "terminal_min": 0.1, "OutEff": 1, "InEff": 1, "energy_value": 5},
        {"bus_id": 3007366, "capacity": 750, "duration": 1, "terminal_max": 0.9, "terminal_min": 0.1, "OutEff": 1, "InEff": 1, "energy_value": 5},
    ]
)
```
### Actual outcome
The output produced by the above code, which may be a screenshot, console output, etc.
![image](https://user-images.githubusercontent.com/49802799/191102492-84824597-448a-45a3-86d3-f3624b9be70d.png)

### Environment
Please specify your platform and versions of the relevant libraries you are using:
* Operating system: Docker

**Comment by BainanXia** [comment]
Hi @Mingze-Li128 , thanks for bringing this up. Learning from the inputs, I could see you are running a scenario with 1 hour interval and 4 storage devices with 1 hour duration. Given the underlying optimization is a multi-period DC OPF, i.e. a sequence of consecutive DC OPF with each of them being 1 hour length, recall the mathematical formulation [here](https://breakthrough-energy.github.io/docs/reisejl/index.html#formulation), my guess is the storage devices will be charged only if the objective function can be further minimized for the single hour, which is rarely the case. Not sure whether it's worth the effort to test it out by creating a scenario with interval length greater than 1 hour?

**Comment by rouille** [comment]
Hi @Mingze-Li128, did you try to increase the interval size as @BainanXia suggested?

**Comment by Mingze-Li128** [comment]
> Hi @Mingze-Li128, did you try to increase the interval size as @BainanXia suggested?

Yes, it seems the results become more meaningful with larger interval. We are doing more testings with gurobi solver.

**Comment by BainanXia** [comment]
Closing this issue as the behavior is as expected based on the current setup.
